# Generated by Django 5.0.1 on 2024-01-30 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={},
        ),
    ]
